---
name: xidots-cli
project_root: "/home/xitonight/Projects/active/xidots-cli"
attach: false
windows:
- main:
    layout: 9f8d,140x35,0,0{70x35,0,0,10,69x35,71,0[69x17,71,0,11,69x17,71,18,13]}
    panes:
      - nvim:
        - cd /home/xitonight/Projects/active/xidots-cli && clear
        - nvim
        - " fR"
      - opencode: 
        - cd /home/xitonight/Projects/active/xidots-cli
        - opencode --port 4000
      - git:
        - cd /home/xitonight/Projects/active/xidots-cli
        - clear && git status
